from . import account_move
from . import account_payment
from . import account_payment_register
from . import hr_contract
from . import hr_employee
from . import hr_kpi_evaluation
from . import hr_payslip
from . import res_company
from . import res_config_settings
