from . import hr_employee
from . import hr_iqama_detail_line
from . import hr_iqama
from . import hr_iqama_approval
from . import hr_iqama_attachment
from . import hr_iqama_family
from . import hr_iqama_history
from . import hr_iqama_fee_wizard
from . import hr_iqama_processing
from . import hr_iqama_type
from . import res_config_settings
