from . import hr_employee
from . import hr_employee_base
from . import hr_holiday_greeting_template
from . import hr_leave_allocation
from . import hr_leave_allowance_rule
from . import hr_leave_type
from . import resource_calendar_leaves
from . import res_company
from . import res_config_settings
