{
    "name": "Check Management",
    "version": "18.0.1.14.0",
    "category": "Accounting/Accounting",
    "summary": "Incoming and outgoing checks: PDC, deposits, collection, bounces, custody and approvals",
    "author": "Sayed Anwar",
    "license": "OPL-1",
    "depends": ["account_accountant", "mail"],
    "data": [
        "security/check_security.xml",
        "security/ir.model.access.csv",
        "data/check_sequence_data.xml",
        "data/check_bounce_reason_data.xml",
        "data/check_payment_method_data.xml",
        "data/check_deposit_sequence_data.xml",
        "data/check_control_sequence_data.xml",
        "data/check_cron_data.xml",
        "data/check_request_sequence_data.xml",
        "views/check_check_views.xml",
        "views/check_event_views.xml",
        "views/check_deposit_views.xml",
        "views/check_control_views.xml",
        "views/check_report_views.xml",
        "views/check_legal_views.xml",
        "views/check_request_views.xml",
        "views/check_dashboard_views.xml",
        "report/check_report_templates.xml",
        "views/check_configuration_views.xml",
        "views/res_config_settings_views.xml",
        "views/account_payment_views.xml",
        "wizard/check_action_wizard_views.xml",
        "wizard/check_allocation_wizard_views.xml",
        "wizard/check_banking_wizard_views.xml",
        "wizard/check_exception_wizard_views.xml",
        "wizard/check_endorsement_wizard_views.xml",
        "wizard/check_import_wizard_views.xml",
        "wizard/check_reallocation_wizard_views.xml",
        "wizard/check_book_import_wizard_views.xml",
        "views/check_menus.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "sa_check_management/static/src/check_dashboard/check_dashboard.js",
            "sa_check_management/static/src/check_dashboard/check_dashboard.xml",
            "sa_check_management/static/src/check_dashboard/check_dashboard.scss",
        ],
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": True,
}
